apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: wahaj123/python
  newTag: "30"
resources:
- deployment-web.yaml
- deployment-db.yaml
- persistentvolumeclaim.yaml
- service-db.yaml
- service-web.yaml
- analysis.yaml
